### ISSUE TITLE
MSN.sol

### ISSUE THREAD

**Issue by haihongS** [daqnext/msn_contracts#1]
- It seems to be `super._transfer`

https://github.com/daqnext/msn_contracts/blob/d784ef1595d7c9b9427b54acf0df04c475df7f70/assets/koa_static/contracts/v2/MSN.sol#L87

- Please use `Format` to keep code clean.
``` Vscode -> MSN.sol -> Right Click -> Format Document ```

**Comment by haihongS** [comment]
@leolikescoding

**Comment by leolikescoding** [comment]
yes , you are right
